name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - docs
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install and Build 🔧
        run: |
          npm install && npm run build

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: master
          FOLDER: docs/.vuepress/dist
